"""cloud ranges

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 23:36:57.523184
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cloud_ranges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("organization", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("cidr", sa.String(length=64), nullable=False),
        sa.Column("ip_version", sa.Integer(), nullable=False),
        sa.Column("region", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=256), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cloud_ranges_provider"), "cloud_ranges", ["provider"], unique=False)
    op.create_index("uq_cloud_range", "cloud_ranges", ["provider", "cidr"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_cloud_range", table_name="cloud_ranges")
    op.drop_index(op.f("ix_cloud_ranges_provider"), table_name="cloud_ranges")
    op.drop_table("cloud_ranges")
    # ### end Alembic commands ###
