"""widen scan trigger

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 23:49:55.841904
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scans", "trigger", existing_type=sa.VARCHAR(length=32), type_=sa.String(length=128), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scans", "trigger", existing_type=sa.String(length=128), type_=sa.VARCHAR(length=32), existing_nullable=False
    )
    # ### end Alembic commands ###
