"""asn ranges

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-04 02:13:51.631172
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asn_ranges",
        sa.Column("start_ip", postgresql.INET(), nullable=False),
        sa.Column("end_ip", postgresql.INET(), nullable=False),
        sa.Column("asn", sa.BigInteger(), nullable=False),
        sa.Column("country", sa.String(length=8), nullable=True),
        sa.Column("organization", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("start_ip"),
    )
    op.create_index(op.f("ix_asn_ranges_asn"), "asn_ranges", ["asn"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_asn_ranges_asn"), table_name="asn_ranges")
    op.drop_table("asn_ranges")
    # ### end Alembic commands ###
